const exercises=[
{n:10,opening:"KID · Mar del Plata · Neo-Classica",fen:"r1bq1rk1/pppnnpbp/3p2p1/3Pp3/2P1P3/2N1B3/PP2BPPP/R2QNRK1 b - - 4 10",last:"10. Be3",question:"Il Bianco sviluppa l’alfiere e sostiene il centro. Qual è la rottura tematica del Nero?",best:"10...f5",answers:["f5","10...f5","...f5"],idea:"...f5 è la rottura caratteristica della Mar del Plata. Il Nero attacca la catena centrale e avvia il controgioco sull’ala di Re prima che il Bianco sfondi con c5.",alts:{nf6:[6,"Mossa sviluppante possibile, ma qui il piano teorico richiede l’immediata ...f5."],a6:[4,"Non è urgente: il Nero deve prima contestare il centro con ...f5."]}},
{n:11,opening:"KID · Mar del Plata · Neo-Classica",fen:"r1bq1rk1/pppnn1bp/3p2p1/3Ppp2/2P1P3/2N1BP2/PP2B1PP/R2QNRK1 b - - 0 11",last:"11. f3",question:"Il Bianco consolida e4. Come guadagna spazio il Nero mantenendo chiuso il centro?",best:"11...f4",answers:["f4","11...f4","...f4"],idea:"...f4 fissa la struttura, guadagna spazio e prepara l’espansione ...g5–g4. Da questo momento i due giocatori attaccano su ali opposte.",alts:{nf6:[6,"È una manovra sensata, ma lascia al Bianco più tempo per organizzare c5."],a6:[4,"Troppo lenta rispetto alla spinta tematica ...f4."]}},
{n:12,opening:"KID · Mar del Plata · Neo-Classica",fen:"r1bq1rk1/pppnn1bp/3p2p1/3Pp3/2P1Pp2/2N2P2/PP2BBPP/R2QNRK1 b - - 1 12",last:"12. Bf2",question:"L’alfiere bianco si ritira. Quale spinta avvia l’attacco di pedoni contro il Re?",best:"12...g5",answers:["g5","12...g5","...g5"],idea:"...g5 sostiene il pedone f4 e prepara ...g4. È una delle immagini più tipiche dell’intera Difesa Est-Indiana: il centro è chiuso e il Nero corre verso il Re.",alts:{nf6:[7,"Manovra teorica e naturale, ma la continuazione più diretta è ...g5."],h6:[4,"Non contribuisce abbastanza rapidamente all’attacco."]}},
{n:13,opening:"KID · Mar del Plata · linea Gligorić",fen:"r1bq1rk1/pppnn1bp/3p4/3Pp1p1/2P1Pp2/2NN1P2/PP2BBPP/R2Q1RK1 b - - 1 13",last:"13. Nd3",question:"Il cavallo bianco sostiene c5. Dove va il cavallo nero per riorganizzare l’attacco?",best:"13...Nf6",answers:["nf6","13...nf6","...nf6"],idea:"...Nf6 riporta il cavallo verso case attive, sostiene l’ala di Re e prepara la manovra ...Ng6, da cui potrà puntare f4 e h4.",alts:{ng6:[7,"La casa g6 è parte del piano, ma nella linea teorica il cavallo d7 passa prima da f6."],a5:[4,"Bloccare l’ala di Donna non è il piano principale di questa posizione."]}},
{n:14,opening:"KID · Mar del Plata · linea Gligorić",fen:"r1bq1rk1/ppp1n1bp/3p1n2/2PPp1p1/4Pp2/2NN1P2/PP2BBPP/R2Q1RK1 b - - 0 14",last:"14. c5",question:"Il Bianco ha ottenuto la rottura c5. Quale manovra mantiene viva l’iniziativa del Nero?",best:"14...Ng6",answers:["ng6","14...ng6","...ng6"],idea:"...Ng6 porta il cavallo verso f4 e h4 e rafforza l’attacco. Il Nero non deve perdere tempi: il Bianco sta già aprendo linee sull’ala di Donna.",alts:{dxc5:[5,"È legale e modifica il centro, ma riduce la tensione e non segue il piano d’attacco principale."],kh8:[5,"Profilassi utile in molte KID, ma qui ...Ng6 è più energica."]}},
{n:15,opening:"KID · Mar del Plata · linea Gligorić",fen:"r1bq1rk1/ppp3bp/3p1nn1/2PPp1p1/4Pp2/2NN1P2/PP2BBPP/2RQ1RK1 b - - 2 15",last:"15. Rc1",question:"Il Bianco occupa la colonna c. Come coordina il Nero la torre per sostenere l’attacco?",best:"15...Rf7",answers:["rf7","15...rf7","...rf7"],idea:"...Rf7 è una tipica manovra della Mar del Plata: la torre protegge la settima traversa e può trasferirsi verso g7 o sostenere l’avanzata dei pedoni contro il Re.",alts:{g4:[7,"Spinta molto tematica, ma nella linea modello la torre viene prima attivata con ...Rf7."],h6:[4,"Mossa lenta che non coordina i pezzi pesanti."]}}
];

const glyphs={k:"♚",q:"♛",r:"♜",b:"♝",n:"♞",p:"♟",K:"♔",Q:"♕",R:"♖",B:"♗",N:"♘",P:"♙"};
let current=0;
const $=id=>document.getElementById(id);

function fenSquares(fen){const out=[];for(const c of fen.split(" ")[0]){if(c==="/")continue;if(/\d/.test(c))out.push(...Array(Number(c)).fill(null));else out.push(c)}return out}
function cleanMove(v){return v.toLowerCase().trim().replace(/[+#?!]/g,"").replace(/\s/g,"")}
function renderBoard(fen){const board=$("board");board.replaceChildren();fenSquares(fen).reverse().forEach((piece,i)=>{const original=63-i,row=Math.floor(original/8),col=original%8,s=document.createElement("div");s.className=`square ${(row+col)%2?"dark":"light"}`;s.title=`${"abcdefgh"[col]}${8-row}`;if(piece){const p=document.createElement("span");p.className=`piece ${piece===piece.toUpperCase()?"white-piece":"black-piece"}`;p.textContent=glyphs[piece];s.appendChild(p)}board.appendChild(s)})}
function render(){const e=exercises[current];$("exerciseNumber").textContent=`ESERCIZIO ${String(current+1).padStart(2,"0")}`;$("moveNumber").textContent=`Mossa ${e.n} del Bianco`;$("opening").textContent=e.opening;$("lastMove").textContent=e.last;$("question").textContent=e.question;$("moveInput").value="";$("feedback").classList.add("hidden");$("solution").classList.add("hidden");renderBoard(e.fen);$("moveInput").focus({preventScroll:true})}
function next(){let n=current;while(n===current)n=Math.floor(Math.random()*exercises.length);current=n;render();window.scrollTo({top:0,behavior:"smooth"})}
function evaluate(event){event.preventDefault();const e=exercises[current],move=cleanMove($("moveInput").value);if(!move){$("moveInput").focus();return}let score,text;if(e.answers.includes(move)){score=10;text="Eccellente: hai trovato la continuazione principale."}else{const short=move.replace(/^\d+\.\.\./,"").replace(/^\.\.\./,"");if(e.alts[short]){[score,text]=e.alts[short]}else{score=3;text="La mossa può essere legale, ma non realizza il piano più urgente della posizione. Cerca la tipica iniziativa della KID."}}$("scoreValue").textContent=score;$("scoreTitle").textContent=score>=9?"Mossa corretta":score>=7?"Buona idea":"Da migliorare";$("scoreText").textContent=text;$("bestMove").textContent=e.best;$("idea").textContent=e.idea;$("feedback").classList.remove("hidden");$("solution").classList.remove("hidden")}

$("newTop").addEventListener("click",next);$("newBottom").addEventListener("click",next);$("answerForm").addEventListener("submit",evaluate);render();
