const exercises=[
{n:10,opening:"Variante Mar del Plata",fen:"r1bq1rk1/ppp1bppp/2np1n2/4p3/2B1P3/2N1BN1P/PPP2PP1/R2Q1RK1 b - - 2 10",last:"10. O-O",question:"Il Bianco ha completato lo sviluppo. Come imposta il Nero il tipico gioco sull’ala di Re?",best:"10...Nh5",answers:["nh5","10...nh5","...nh5"],idea:"Il cavallo libera il pedone f e prepara ...f5, il piano tematico della KID. Il Nero accetta meno spazio al centro per creare controgioco diretto sull’ala di Re.",alts:{ne8:[8,"Piano tematico e giocabile: sostiene ...f5, ma è meno attivo in questa posizione."],a6:[5,"Mossa utile in alcune linee, ma qui è troppo lenta rispetto all’urgenza di ...f5."]}},
{n:11,opening:"Mar del Plata · piano classico",fen:"r1bq1rk1/ppp1bppp/2np4/4p2n/2B1P3/2N1BN1P/PPP2PP1/R2Q1RK1 b - - 0 11",last:"11. Re1",question:"Il Nero ha già portato il cavallo in h5. Qual è la rottura strategica che dà senso alla posizione?",best:"11...f5",answers:["f5","11...f5","...f5"],idea:"...f5 è la rottura fondamentale: attacca il centro e apre linee verso il Re bianco. Rimandarla permetterebbe al Bianco di consolidare lo spazio.",alts:{kh8:[6,"Mossa profilattica nota, ma la posizione richiede subito la rottura ...f5."],a6:[4,"Non affronta il centro e concede tempo al Bianco."]}},
{n:12,opening:"Mar del Plata · centro chiuso",fen:"r1bq1rk1/ppp1b1pp/2np4/4pp1n/2B1P3/2N1BN1P/PPP2PP1/R2QR1K1 b - - 0 12",last:"12. Re1",question:"Con il centro bloccato, quale mossa mette al sicuro il Re nero e prepara l’attacco?",best:"12...Kh8",answers:["kh8","12...kh8","...kh8"],idea:"...Kh8 è una profilassi tipica: sottrae il Re a possibili tatticismi e sostiene l’espansione con ...g5 e ...Nf4.",alts:{g5:[8,"È coerente con l’attacco, ma ...Kh8 rende prima il piano più solido."],nf6:[3,"Ritirarsi perde il senso del cavallo in h5 e riduce la pressione."]}},
{n:13,opening:"KID classica · attacco sul Re",fen:"r1bq1r1k/ppp1b1pp/2np4/4pp1n/2B1P3/2N1BN1P/PPP2PP1/R2QR1K1 b - - 2 13",last:"13. a4",question:"Il Bianco inizia il gioco sull’ala di Donna. Come deve reagire il Nero?",best:"13...g5",answers:["g5","13...g5","...g5"],idea:"Le ali corrono in direzioni opposte. ...g5 guadagna spazio, sostiene il cavallo h5 e prepara ...g4 o ...Nf4: il Nero deve creare minacce.",alts:{a5:[5,"Rallenta il Bianco ma devia dal piano principale sull’ala di Re."],nf6:[2,"Rinuncia al controgioco proprio quando il Bianco accelera sull’altra ala."]}},
{n:14,opening:"KID classica · manovra d’attacco",fen:"r1bq1r1k/ppp1b2p/2np4/4pppn/P1B1P3/2N1BN1P/1PP2PP1/R2QR1K1 b - - 0 14",last:"14. b4",question:"Il Bianco guadagna spazio a Ovest. Qual è la casa ideale per il cavallo nero d’attacco?",best:"14...Nf4",answers:["nf4","14...nf4","...nf4"],idea:"Da f4 il cavallo punta h3 e g2, coordina l’attacco con Donna e alfiere e può provocare concessioni. È una manovra tematica della Mar del Plata.",alts:{g4:[8,"Spinta coerente e pericolosa, ma ...Nf4 aumenta prima la pressione sui punti deboli."],a5:[4,"Contenere l’ala di Donna è secondario rispetto all’attacco al Re."]}},
{n:15,opening:"KID classica · punto di rottura",fen:"r1bq1r1k/ppp1b2p/2np4/4pppn/PpB1P3/2N1BN1P/2P2PP1/R2QR1K1 b - - 0 15",last:"15. b5",question:"Il Bianco ha chiuso l’ala di Donna. Quale spinta apre linee contro il suo Re?",best:"15...g4",answers:["g4","15...g4","...g4"],idea:"...g4 scaccia il cavallo f3, indebolisce le case chiare e apre colonne per i pezzi pesanti. Nelle posizioni a centro chiuso, il tempo dell’attacco è decisivo.",alts:{nf4:[8,"Manovra molto naturale; ...g4 è però la continuazione più energica immediata."],a5:[3,"Il Bianco ha già fissato la struttura: serve creare minacce sull’altra ala."]}}
];

const glyphs={k:"♚",q:"♛",r:"♜",b:"♝",n:"♞",p:"♟",K:"♔",Q:"♕",R:"♖",B:"♗",N:"♘",P:"♙"};
let current=0;
const $=id=>document.getElementById(id);

function fenSquares(fen){const out=[];for(const c of fen.split(" ")[0]){if(c==="/")continue;if(/\d/.test(c))out.push(...Array(Number(c)).fill(null));else out.push(c)}return out}
function cleanMove(v){return v.toLowerCase().trim().replace(/[+#?!]/g,"").replace(/\s/g,"")}
function renderBoard(fen){const board=$("board");board.replaceChildren();fenSquares(fen).reverse().forEach((piece,i)=>{const original=63-i,row=Math.floor(original/8),col=original%8,s=document.createElement("div");s.className=`square ${(row+col)%2?"dark":"light"}`;s.title=`${"abcdefgh"[col]}${8-row}`;if(piece){const p=document.createElement("span");p.className=`piece ${piece===piece.toUpperCase()?"white-piece":"black-piece"}`;p.textContent=glyphs[piece];s.appendChild(p)}board.appendChild(s)})}
function render(){const e=exercises[current];$("exerciseNumber").textContent=`ESERCIZIO ${String(current+1).padStart(2,"0")}`;$("moveNumber").textContent=`Mossa ${e.n} del Bianco`;$("opening").textContent=e.opening;$("lastMove").textContent=e.last;$("question").textContent=e.question;$("moveInput").value="";$("feedback").classList.add("hidden");$("solution").classList.add("hidden");renderBoard(e.fen);$("moveInput").focus({preventScroll:true})}
function next(){let n=current;while(n===current)n=Math.floor(Math.random()*exercises.length);current=n;render();window.scrollTo({top:0,behavior:"smooth"})}
function evaluate(event){event.preventDefault();const e=exercises[current],move=cleanMove($("moveInput").value);if(!move){$("moveInput").focus();return}let score,text;if(e.answers.includes(move)){score=10;text="Eccellente: hai trovato la continuazione principale."}else{const short=move.replace(/^\d+\.\.\./,"").replace(/^\.\.\./,"");if(e.alts[short]){[score,text]=e.alts[short]}else{score=3;text="La mossa può essere legale, ma non realizza il piano più urgente della posizione. Cerca la tipica iniziativa della KID."}}$("scoreValue").textContent=score;$("scoreTitle").textContent=score>=9?"Mossa corretta":score>=7?"Buona idea":"Da migliorare";$("scoreText").textContent=text;$("bestMove").textContent=e.best;$("idea").textContent=e.idea;$("feedback").classList.remove("hidden");$("solution").classList.remove("hidden")}

$("newTop").addEventListener("click",next);$("newBottom").addEventListener("click",next);$("answerForm").addEventListener("submit",evaluate);render();
